version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge
    ports:
      - "3306:3306"
      
  airflow-webserver:
    image: apache/airflow:1.10.15
    container_name: airflow_webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/scripts:/usr/local/airflow/scripts
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: webserver

  airflow-scheduler:
    image: apache/airflow:1.10.15
    container_name: airflow_scheduler
    restart: unless-stopped
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/scripts:/usr/local/airflow/scripts
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: scheduler